### ISSUE TITLE
Joker Stencil Big Mult calculated incorrectly for dupes

### ISSUE THREAD

**Issue by runciman** [EFHIII/balatro-calculator#69]
When duplicate Joker Stencil jokers are in play, the big mult is calculcated wrongly. In my example game, I have two Joker Stencil's and the game caluclates the bug mult to be X3, but balatro-calculator reports X4. I've attached a save of the game to demonstrate too
![Screenshot 2024-06-30 175629](https://github.com/EFHIII/balatro-calculator/assets/22504602/ba1cb786-95f6-44fe-8a7d-e17ce400df6d)
![Screenshot 2024-06-30 175644](https://github.com/EFHIII/balatro-calculator/assets/22504602/c3779f55-ea19-4c34-a095-54e506a3cfd5)
[joker stencil save.zip](https://github.com/user-attachments/files/16045504/joker.stencil.save.zip)

**Comment by EFHIII** [comment]
Not a bug. The mult is determined solely by the card's `Value`. You might notice that `Negative` isn't an option. Because Negative cards would effect this, it's not possible to have both no `Negative` option and automatically calculate the mult for this card. I opted to not have negative as an option.
![image](https://github.com/EFHIII/balatro-calculator/assets/20879009/582ac877-9345-48d5-a184-c467a4a4f4d3)
