### ISSUE TITLE
Number of times poker hand has been played

### ISSUE THREAD

**Issue by EFHIII** [EFHIII/balatro-calculator#8]
**Description of the bug**
There should be UI for how many times a hand has been played.
This is necessary for Supernova, Obelisk, and some boss blinds

**Steps To Reproduce**
https://efhiii.github.io/balatro-calculator/?h=QAAkByKAAoYDQCgJACA

**Comment by Lawgikill** [comment]
Not sure if this is a bug vs an enhancement -- not that the label matters.
But really, if you start adding in a UI for how many times a hand has been played, you're getting into the realm of turning this from a calculator to more of a "simulator". If that's the case, you might consider wanting to add another feature. A "Play Hand" button, which would then add +1 to the hand type into the UI in question. It would then remove those cards from hand for you (instead of having to do it manually). Would be pretty dope I think. It also would go hand in hand with a lot of the other enhancements you're talking about, like tracking money and cards that give you money, etc.

**Comment by EFHIII** [comment]
Supernova and Obelisk can't work without this, so I consider it more of a bug.
